### PR TITLE
Use prop-types library

### PR DESCRIPTION
**Pull request by developer239**

### CODE REVIEW

**Comment by daveols** [comment]
Happy to do this, but is there any pressing need to move on to the new library? Also you'd need to put it in the package.json.

**Comment by developer239** [comment]
Of course there is. You did not specify version of react in your package json so no one with react 16+ can use this library. I am unable to run `yarn install` because there are still like 5 libraries waiting for the prop types package. :)

**Comment by daveols** [comment]
@developer239 fair enough. Add it to the dependencies and I'll release it.

**Comment by Hunsu** [comment]
I did it in https://github.com/localz/react-native-searchbar/pull/39

**Pull request merged**
