### PR TITLE
adding in changing keyboard appearance

### PR DESCRIPTION
**Pull request by ste00martin**
I've got a personal project which needs this

### CODE REVIEW

**Comment by sbdm05** [comment]
Hello
How can we remove the keyboard from appearing when not typing ? In my case, as soon as the app opens, the keyboard pops up. I would like to change that. 
Thanks

**Comment by aviggiano** [comment]
@daveols I just saw this PR, which is quite similar to mine, and I wondered if it wouldn't be better to accept a `textInputProps` that would be spread (`{...textInputProps}`) to the `TextInput` together with the rest of the default properties. 

This way each user could customize their own searchbars instead of explicitly supporting every single key.

**Comment by daveols** [comment]
@aviggiano I've thought about doing this for a while but haven't had time. It's definitely the right approach.

**Comment by daveols** [comment]
@sbdm05 look into focusOnLayout

**Pull request merged**
